# Generated by Django 5.0.6 on 2024-05-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_operator', models.CharField(choices=[('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>='), ('==', '==')], max_length=2)),
                ('Temperature', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
    ]
